# Generated by Django 3.1.3 on 2020-11-21 05:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_auto_20201119_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Performance',
            new_name='Previous_Score',
        ),
        migrations.DeleteModel(
            name='one',
        ),
    ]
