# Generated by Django 3.1.3 on 2020-11-26 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_previous_score2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Previous_Score2',
            new_name='Previous_Score_Num',
        ),
    ]
