# Generated by Django 3.1.3 on 2020-11-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201126_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Accuracy',
            new_name='Accuracy1',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='C_pm',
            new_name='C_pm1',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Errors',
            new_name='Errors1',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Time',
            new_name='Time1',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='W_pm',
            new_name='W_pm1',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='manager',
            new_name='manager1',
        ),
    ]
