# Generated by Django 3.1.3 on 2020-11-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20201126_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Accuracy1',
            new_name='Accuracy',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='C_pm1',
            new_name='C_pm',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Errors1',
            new_name='Errors',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='Time1',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='previous_score_num',
            old_name='W_pm1',
            new_name='W_pm',
        ),
    ]
