# Generated by Django 3.1.3 on 2020-11-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201126_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Previous_Score_Num',
        ),
    ]
